name: Code Quality

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install quality tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy bandit safety

    - name: Check code formatting with Black
      run: black --check --diff translators/ cli.py tests/

    - name: Check import sorting with isort
      run: isort --check-only --diff translators/ cli.py tests/

    - name: Lint with flake8
      run: flake8 translators/ cli.py tests/ --max-line-length=88 --extend-ignore=E203,W503

    - name: Type check with mypy
      run: mypy translators/ cli.py --ignore-missing-imports

    - name: Security check with bandit
      run: bandit -r translators/ cli.py tests/ -f json -o bandit-report.json || true

    - name: Check for vulnerable dependencies
      run: safety check --output json || true

    - name: Upload security reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install documentation tools
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme

    - name: Build documentation
      run: |
        mkdir -p docs
        sphinx-build -b html docs docs/_build/html || true

    - name: Upload documentation
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html/