name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*

    - name: Create GitHub release notes
      if: github.event_name == 'release'
      run: |
        echo "🚀 Released version ${{ github.event.release.tag_name }}" >> release_notes.md
        echo "" >> release_notes.md
        echo "## What's New" >> release_notes.md
        echo "" >> release_notes.md
        echo "${{ github.event.release.body }}" >> release_notes.md
        echo "" >> release_notes.md
        echo "## Installation" >> release_notes.md
        echo "" >> release_notes.md
        echo "\`\`\`bash" >> release_notes.md
        echo "pip install code-snippet-translator" >> release_notes.md
        echo "\`\`\`" >> release_notes.md

    - name: Upload release notes
      if: github.event_name == 'release'
      uses: actions/upload-artifact@v3
      with:
        name: release-notes
        path: release_notes.md